[package]
name = "lottie-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde_json = "1.0.139"
thiserror = "2.0.11"
paste = "1.0.15"

[dev-dependencies]
serde = { version="1.0.218", features = ["derive"]}

